### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by teraoo** [TeraProxy/Inspector#5]
pinkie proxy

![t](https://user-images.githubusercontent.com/40299748/63376189-82933000-c38d-11e9-8ba9-6ebb1ef14305.JPG)

**Comment by TeraProxy** [comment]
My modules are tested on Caali's TERA Toolbox only. Looks like Pinkie didn't update his definition files yet. You can manually download the updated tera-data from Caali, simply switch over to TERA Toolbox or ask Pinkie to update.
