### ISSUE TITLE
Hello, doesnt seem to work for me. I am in EU.

### ISSUE THREAD

**Issue by Zezo12345** [TeraProxy/Inspector#6]
![image](https://user-images.githubusercontent.com/50622671/63785974-85dc6d80-c8f1-11e9-81ae-3fc52671486e.png)

**Comment by Zezo12345** [comment]
![image](https://user-images.githubusercontent.com/50622671/63786018-97257a00-c8f1-11e9-9423-510c1a0b0f82.png)

**Comment by Zezo12345** [comment]
Inspected someone with clears but it shows he doesn't have any.

**Comment by TeraProxy** [comment]
Thanks, I'll look into it. They might have changed the dungeon IDs around.

**Comment by TeraProxy** [comment]
I'm actually impressed. Looks like they actually fixed something. The server doesn't send you info about other people's clears any longer (they send you 0 for every dungeon). So no issue on our end, Krafton/Bluehole simply removed the possibility of showing the clear count.

I will upload a new version that shows rookie/skilled status instead.
